apiVersion: v1
entries:
  ollama:
  - annotations:
      artifacthub.io/category: ai-machine-learning
      artifacthub.io/changes: |
        - kind: changed
          description: upgrade app version to 0.3.14
    apiVersion: v2
    appVersion: 0.3.14
    created: "2024-10-25T17:41:16.25541+02:00"
    description: Get up and running with large language models locally.
    digest: 6f345baa25fd444ed099565cd388d980ff11c36a32b6ac30d6b8fcfaa455a634
    home: https://ollama.ai/
    icon: https://ollama.ai/public/ollama.png
    keywords:
    - ai
    - llm
    - llama
    - mistral
    kubeVersion: ^1.16.0-0
    maintainers:
    - email: contact@otwld.com
      name: OTWLD
    name: ollama
    sources:
    - https://github.com/ollama/ollama
    - https://github.com/otwld/ollama-helm
    type: application
    urls:
    - https://mbtraore.github.io/helm-openwebui-charts/ollama-0.63.0.tgz
    version: 0.63.0
  open-webui:
  - annotations:
      licenses: MIT
    apiVersion: v2
    appVersion: 0.1.107
    created: "2024-10-25T17:41:16.26395+02:00"
    dependencies:
    - condition: ollama.enabled
      name: ollama
      repository: https://otwld.github.io/ollama-helm/
      version: 0.63.0
    description: "Chart to deploy Open WebUI, a ChatGPT-Style Web UI Client for Ollama
      \U0001F999."
    digest: 6e6417ae2b07eaedb79c228fcb0b939de54a2bd2ee4a5a6200885b1b91b31c3d
    home: https://openwebui.com/
    icon: https://openwebui.com/favicon.png/
    keywords:
    - ai
    - ollama
    - llm
    - llama
    maintainers:
    - email: mbarre.traore-ext@iledefrance-mobilites.fr
      name: mbtraore
      url: https://mbarre.fr
    name: open-webui
    sources:
    - https://github.com/jmorganca/ollama/
    - https://github.com/open-webui/open-webui
    - https://github.com/braveokafor/open-webui-helm/
    urls:
    - https://mbtraore.github.io/helm-openwebui-charts/open-webui-3.4.0.tgz
    version: 3.4.0
generated: "2024-10-25T17:41:16.253978+02:00"
